[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterCitations = "daee34ce-89f3-4625-b898-19384cb65244"
FiniteKernels = "2ee73795-50db-4096-9573-22982ed4949b"
MarkovCategories = "89535b7d-47b5-4a7c-ab85-485cba9d75b9"

[compat]
Documenter = "1"
DocumenterCitations = "1"

[sources]
MarkovCategories = {path = ".."}
FiniteKernels = {path = "../../FiniteKernels.jl"}
